public class Character {
  public String name;
  public Species species;
  public int level;
  public int maxhp = 1;
  public int currenthp = 1;
  public int fort;
  public int ref;
  public int will;
  public int bab;
  public String alignment;
  public int strength;
  public int dexterity;
  public int constitution;
  public int intelligence;
  public int wisdom;
  public int charisma;
  public int grappled;
  public int fatigued;
  public int exhausted;
  public int unconscious;
  public int shaken;
  public int frightened;
  public int panicked;
  public int existingcomfortablycold;
  public int existingcomfortablyhot;
  public int existcomfortablycold;
  public int existcomfortablyhot;
  public int protection;
  public String protectionfrom;
  public int resisting;
  public String resistenergy;
  public Curse[] curses = new Curse[10];
  public int damagereducting;
  public int dr;
  public int badmagiceffects;
  public boolean stabilized;
  public boolean obscured;
  public boolean poisoned;
  public boolean diseased;
  public int negativelevels;
  public int oneattacksaveskillcheck;
  public boolean readmagic;
  public String detecting;
  public boolean detect;
  public boolean tongues;
  public boolean commune;
  public boolean trueseeing;
  public boolean attackrollfearsavebonus;
  public boolean commanded;
  public int sleep;
  public int entrancing;
  public int light;
  public int invisibility; 
  public int mirrorimage;
  public String polymorph;
  public Character(String name, Species species, int level, String alignment, int strength, int dexterity, int constitution, int intelligence, int wisdom, int charisma) {
    this.name = name;
    this.species = species;
    this.level = level;
    this.maxhp = 1;
    this.currenthp = 1;
    this.fort = (int) Math.floor(level/3);
    this.ref = (int) Math.floor(level/3);
    this.will = (int) Math.floor(level/2)+2;
    this.bab = (int) Math.floor(level/2);
    this.alignment = alignment;
    this.strength = strength + this.species.strength;
    this.dexterity = dexterity + this.species.dexterity;
    this.constitution = constitution + this.species.constitution;
    this.intelligence = intelligence + this.species.intelligence;
    this.wisdom = wisdom + this.species.wisdom;
    this.charisma = charisma + this.species.charisma;
    this.grappled = 0;
    this.fatigued = 0;
    this.exhausted = 0;
    this.unconscious = 0;
    this.shaken = 0;
    this.frightened = 0;
    this.panicked = 0;
    this.existingcomfortablycold = 0;
    this.existingcomfortablyhot = 0;
    this.existcomfortablycold = 33;
    this.existcomfortablyhot = 94;
    this.protection = 0;
    this.protectionfrom = "none";
    this.resisting = 0;
    this.resistenergy = "none";
    this.curses = new Curse[10];
    this.damagereducting = 0;
    this.dr = 0;
    this.badmagiceffects = 0;
    this.stabilized = true;
    this.obscured = false;
    this.poisoned = false;
    this.diseased = false;
    this.negativelevels = 0;
    this.oneattacksaveskillcheck = 0;
    this.readmagic = false;
    this.detecting = "none";
    this.detect = false;
    this.tongues = false;
    this.commune = false;
    this.trueseeing = false;
    this.attackrollfearsavebonus = false;
    this.commanded = false;
    this.sleep = 0;
    this.entrancing = 0;
    this.light = 0;
    this.invisibility = 0; 
    this.mirrorimage = 0;
    this.polymorph = "none";
  }
  public void leveling(int amount) {
    this.level += amount;
    this.fort = (int) Math.floor(level/3);
    this.ref = (int) Math.floor(level/3);
    this.will = (int) Math.floor(level/2)+2;
    this.bab = (int) Math.floor(level/2);
  } 
}
